- name: Generate Overview | Set Facts
  set_fact:
    port_mapping: ""

- name: Extract Overview
  command: python3 '{{role_path}}/scripts/extract_overview.py'
  args:
    stdin: '{{ podman.apps | to_json }}'
  register: overview_result
  changed_when: false

- name: Convert Overview Result to Ansible Variable
  set_fact:
    overview: '{{overview_result.stdout | from_json}}'

- name: Save Port Mapping
  copy:
    content: '{{overview.ports_mapping | to_yaml}}'
    dest: '{{system_path}}/podman_app_ports_mapping.yaml'

- name: Save Suggested Next Ports
  copy:
    content: '{{overview.suggested_ports | to_nice_yaml}}'
    dest: '{{system_path}}/suggested_ports.yaml'
