- name: Install Podman and Related Tools
  import_tasks: ../tasks/yay.yml
  vars:
    package_s:
      - podman
      - docker-compose
      - podman-dnsname
      - slirp4netns
      - crun
      - firewalld

- name: Set Podman Envs
  import_tasks: ../tasks/add-fish-conf.yml
  vars:
    file_s: podman
    content: |
      set -gx CONTAINERS_COLOR {{podman.conf.envs.color}}
      set -gx DOCKER_HOST unix://$XDG_RUNTIME_DIR/podman/podman.sock

- name: 'Prepare Containers Dir'
  block:
    - name: Create Containers Dir
      file:
        path: '{{podman.paths.containers}}'
        state: directory
        mode: '0755'

    - name: Conf registries.conf
      copy:
        dest: '{{podman.paths.containers}}/registries.conf'
        mode: '0644'
        content: unqualified-search-registries = {{podman.conf.registries.unqualifieds}}

    - name: Conf containers.conf
      copy:
        dest: '{{podman.paths.containers}}/containers.conf'
        mode: '0644'
        content: |
          [engine]
          compose_warning_logs={{podman.conf.compose.warning_logs}}

- name: Prepare Podman Dir
  block:
    - name: Create Podman Dir
      file:
        path: '{{podman.paths.mounts}}'
        state: directory
        owner: '{{linux_user}}'
        group: '{{linux_user}}'
        recurse: true
      become: true

    - name: Check Podman Namespace Ownership
      stat:
        path: '{{podman.paths.mounts}}/.namespace-owned'
      register: podman_path_stat

    - name: Set Podman namespace ownership
      when: not podman_path_stat.stat.exists
      block:
        - name: Podman Unshare
          command:
            cmd: 'podman unshare chown -R 0:0 {{podman.paths.mounts}}'

        - name: Create Namespace Ownership Marker
          file:
            path: '{{podman.paths.mounts}}/.namespace-owned'
            state: touch
