- name: Install Podman and Related Tools
  import_tasks: ../tasks/yay.yml
  vars:
    package_s: [podman, docker-compose]

- name: Set Podman Envs
  import_tasks: ../tasks/add-fish-conf.yml
  vars:
    file_s: podman
    content: |
      set -gx CONTAINERS_COLOR 1
      set -gx DOCKER_HOST unix://$XDG_RUNTIME_DIR/podman/podman.sock
