abbr -a -- tag  'tmsu tag'
abbr -a -- tags 'tmsu tags'
abbr -a -- tagi 'tmsu init'
abbr -a -- tagm 'tmsu mount'
abbr -a -- tagu 'tmsu unmount'
abbr -a -- tagf 'tmsu files'
abbr -a -- tagd 'tmsu delete'
abbr -a -- tagx 'xargs -I @ tmsu tag @'