- name: 'Make 9 virtual desktops in 3x3 grid'
  shell: |
    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Number 9
    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Rows 3
  changed_when: false
  tags:
    - virtual-desktops

- name: 'Name virtual desktops'
  shell: |
    kwriteconfig6 --file {{kwinrc_path}} \
    --group Desktops \
    --key Name_1 ┛

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_2 ┻

    kwriteconfig6 --file {{kwinrc_path}} \
      --group  Desktops \
      --key Name_3 ┗

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_4 ┫

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_5 ╋

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_6 ┣

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_7 ┓

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_8 ┳

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Desktops \
      --key Name_9 ┏
  changed_when: false
  tags:
    - virtual-desktops

- name: 'Turn wrapping arround on for virtual desktops'
  shell: |
    kwriteconfig6 --file {{kwinrc_path}} \
      --group Windows \
      --key RollOverDesktops true
  changed_when: false
  tags:
    - virtual-desktops

- name: 'Set virtual desktop name display time'
  shell: |
    kwriteconfig6 --file {{kwinrc_path}} \
      --group Plugins \
      --key desktopchangeosdEnabled true

    kwriteconfig6 --file {{kwinrc_path}} \
      --group Script-desktopchangeosd \
      --key PopupHideDelay 500
  changed_when: false
  tags:
    - virtual-desktops

- name: Disable desktop layout indicator
  shell: |
    kwriteconfig6 --file {{kwinrc_path}} \
      --group Script-desktopchangeosd \
      --key TextOnly true
  changed_when: false
  tags:
    - virtual-desktops

- name: Reconfigure virtual desktops
  command: qdbus6 org.kde.KWin /KWin org.kde.KWin.reconfigure
  changed_when: false
  tags:
    - virtual-desktops
