- name: Install Fcitx5 via yay
  kewlfft.aur.aur:
    name:
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - fcitx5-chinese-addons
    state: present
  become: true
  become_user: '{{linux_user}}'
  tags:
    - install
    - fcitx

- name: Set Fcitx5 Wayland virtual keyboard
  ini_file:
    path: '{{user_path}}/.config/kwinrc'
    section: Wayland
    option: 'InputMethod[$e]'
    value: /usr/share/applications/fcitx5-wayland-launcher.desktop

- name: Establish Fcitx Conf
  copy:
    src: 'fcitx5/'
    dest: '{{user_path}}/.config/fcitx5/'
    mode: '0644'
    directory_mode: '0755'
  tags:
    - fcitx
    - conf

- name: Add Shell Conf
  copy:
    src: 'fcitx.fish'
    dest: '{{fish_path}}/conf.d'
    mode: '0644'
    force: false
  tags:
    - fcitx
    - fish
    - shell
