- name: Install fcitx via yay
  kewlfft.aur.aur:
    name:
      - fcitx5
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - fcitx5-chinese-addons
    state: present
  become: true
  become_user: '{{linux_user}}'
  tags:
    - install
    - fcitx

- name: Add Shell Conf
  copy:
    src: 'fcitx.fish'
    dest: '{{fish_path}}/conf.d'
    mode: '0644'
    force: false
  tags:
    - fcitx
    - fish
    - shell
