## bat/cat
abbr -a -- cat  'bat'
abbr -a -- ba   'bat'
abbr -a -- b    'bat'
abbr -a -- batm 'bat --style header,grid,numbers'
abbr -a -- bam  'bat --style header,grid,numbers'
abbr -a -- bm   'bat --style header,grid,numbers'
abbr -a -- bal  'bat -l'
abbr -a -- baly 'bat -l yaml'
abbr -a -- balj 'bat -l json'
abbr -a -- balt 'bat -l toml'
abbr -a -- bali 'bat -l toml'
abbr -a -- bl   'bat -l'
abbr -a -- bly  'bat -l yaml'
abbr -a -- blj  'bat -l json'
abbr -a -- blt  'bat -l toml'
abbr -a -- bli  'bat -l ini'
abbr -a -- bml  'bat --style header,grid,numbers -l'
abbr -a -- bmly 'bat --style header,grid,numbers -l yaml'
abbr -a -- bmlj 'bat --style header,grid,numbers -l json'
abbr -a -- bmlt 'bat --style header,grid,numbers -l toml'
abbr -a -- bmli 'bat --style header,grid,numbers -l ini'
## less
alias less      'bat --paging=always'
abbr -a --position anywhere -- \\less    '| less'
abbr -a --position anywhere -- \\les     '| less'
abbr -a --position anywhere -- \\le      '| less'
abbr -a --position anywhere -- \\l       '| less'
