abbr -a -- g   'grep'
abbr -a -- gi  'grep -i'
abbr -a -- ge  'grep -E'
abbr -a -- gv  'grep -v'
abbr -a -- gve 'grep -vE'
abbr -a --position anywhere -- \\g    '| grep'
abbr -a --position anywhere -- \\gi   '| grep -i'
abbr -a --position anywhere -- \\ge   '| grep -E'
abbr -a --position anywhere -- \\gv   '| grep -v'
abbr -a --position anywhere -- \\gve  '| grep -vE'