abbr -a -- ls     'lsd'
abbr -a -- l      'lsd'
abbr -a -- la     'lsd -A'
abbr -a -- ll     'lsd -lh'
abbr -a -- lla    'lsd -lhA'
abbr -a -- lld    'lsd -lhd'
abbr -a -- lwc    'lsd | wc'
abbr -a -- lwcl   'lsd | wc -l'
abbr -a -- lwcc   'lsd | wc -c'
abbr -a -- lg     'lsd | grep'
abbr -a -- lsg    'lsd | grep'
abbr -a -- lge    'lsd | grep -E'
abbr -a -- lgi    'lsd | grep -i'
abbr -a -- lgv    'lsd | grep -v'
abbr -a -- lgve   'lsd | grep -vE'
abbr -a -- lgvi   'lsd | grep -vi'
abbr -a -- lgiv   'lsd | grep -iv'
abbr -a -- llg    'lsd -lh | grep'
abbr -a -- llag   'lsd -lhA | grep'
abbr -a -- lag    'lsd -A | grep'
abbr -a -- lalg   'lsd -Alh | grep'
abbr -a -- llgi   'lsd -lh | grep -i'
abbr -a -- llgv   'lsd -lh | grep -v'
