## podman
abbr -a -- p       'podman'
abbr -a -- po      'podman'
abbr -a -- pod     'podman'
abbr -a -- podm    'podman'
abbr -a -- prun    'podman run'
abbr -a -- pru     'podman run'
abbr -a -- p1      'podman start'
abbr -a -- p0      'podman stop'
abbr -a -- p1f     'podman start -f'
abbr -a -- p0f     'podman stop -f'
abbr -a -- p1fl    'podman start -f label='
abbr -a -- p0fl    'podman stop -f label='
abbr -a -- p1fla   'podman start -f label=app='
abbr -a -- p0fla   'podman stop -f label=app='
abbr -a -- p1a     'podman start -f label=app='
abbr -a -- p0a     'podman stop -f label=app='
abbr -a -- p1l     'podman start -f label='
abbr -a -- p0l     'podman stop -f label='
abbr -a -- p01     'podman restart'
abbr -a -- p10     'podman restart'
abbr -a -- pps     'podman ps --format $PODMAN_FORMATTING'
abbr -a -- ppsa    'podman ps --format $PODMAN_FORMATTING -a'
abbr -a -- ppsf    'podman ps --format $PODMAN_FORMATTING --filter'
abbr -a -- ppsaf   'podman ps --format $PODMAN_FORMATTING -a --filter'
abbr -a -- ppsfl   'podman ps --format $PODMAN_FORMATTING --filter label'
abbr -a -- ppsafl  'podman ps --format $PODMAN_FORMATTING -a --filter label'
abbr -a -- ppsg    'podman ps | grep'
abbr -a -- ppsag   'podman ps -a | grep'
abbr -a -- pk      'podman kill'
abbr -a -- prm     'podman rm'
abbr -a -- prmi    'podman rmi'
abbr -a -- pl      'podman logs'
abbr -a -- pe      'podman exec'
abbr -a -- pg      'podman generate'
abbr -a -- pgs     'podman generate systemd'
abbr -a -- pgsf    'podman generate systemd --files'
abbr -a -- pgsn    'podman generate systemd -n'
abbr -a -- pgsfn   'podman generate systemd --files -n'
abbr -a -- pimgs   'podman images'
abbr -a -- pimgsg  'podman images | grep'
abbr -a -- pimg    'podman image'
abbr -a -- pimgrm  'podman image rm'
abbr -a -- pimgr   'podman image rm'
abbr -a -- pi      'podman inspect'
abbr -a -- ppod    'podman pod'
abbr -a -- ppo     'podman pod'
abbr -a -- ppodc   'podman pod create'
abbr -a -- ppoc    'podman pod create'
abbr -a -- ppodps  'podman pod ps'
abbr -a -- ppops   'podman pod ps'
abbr -a -- ppodrm  'podman pod rm'
abbr -a -- pporm   'podman pod rm'
abbr -a -- pb      'podman build'
abbr -a -- pbt     'podman build -t'
abbr -a -- pn      'podman network'
abbr -a -- pnc     'podman network create'
abbr -a -- pnrm    'podman network rm'
abbr -a -- pnls    'podman network ls'
abbr -a -- pnl     'podman network ls'
abbr -a -- pni     'podman network inspect'
abbr -a -- pnp     'podman network prune'
abbr -a -- pv      'podman volume'
abbr -a -- pvc     'podman volume create'
abbr -a -- pve     'podman volume export'
abbr -a -- pvl     'podman volume ls'
abbr -a -- pvls    'podman volume ls'
abbr -a -- pvrm    'podman volume rm'
abbr -a -- pvi     'podman volume inspect'
abbr -a -- pq      'podman quadlet'
abbr -a -- pql     'podman quadlet list'
abbr -a -- pqls    'podman quadlet list'
abbr -a -- pqi     'podman quadlet install'
abbr -a -- pc      'podman compose'
abbr -a -- pcp     'podman compose -p'
abbr -a -- pcu     'podman compose up'
abbr -a -- pcub    'podman compose up --build'
abbr -a -- pcd     'podman compose down'
abbr -a -- pc0     'podman compose stop'
abbr -a -- pc1     'podman compose start'
abbr -a -- pc01    'podman compose restart'
abbr -a -- pc10    'podman compose restart'
abbr -a -- pcps    'podman compose ps --format $PODMAN_FORMATTING'
abbr -a -- pcpsa   'podman compose ps --format $PODMAN_FORMATTING -a'
abbr -a -- pcrm    'podman compose rm'
## containers
abbr -a -- p1g     'podman start graphdb'
abbr -a -- p0g     'podman stop graphdb'
