## podman
abbr -a -- p       'podman'
abbr -a -- po      'podman'
abbr -a -- pod     'podman'
abbr -a -- podm    'podman'
abbr -a -- prun    'podman run'
abbr -a -- pru     'podman run'
abbr -a -- p1      'podman start'
abbr -a -- p0      'podman stop'
abbr -a -- p01     'podman restart'
abbr -a -- p10     'podman restart'
abbr -a -- pps     'podman ps'
abbr -a -- ppsa    'podman ps -a'
abbr -a -- ppsf    'podman ps --filter'
abbr -a -- ppsaf   'podman ps -a --filter'
abbr -a -- ppsfl   'podman ps --filter label'
abbr -a -- ppsafl  'podman ps -a --filter label'
abbr -a -- ppsg    'podman ps | grep'
abbr -a -- ppsag   'podman ps -a | grep'
abbr -a -- pk      'podman kill'
abbr -a -- prm     'podman rm'
abbr -a -- prmi    'podman rmi'
abbr -a -- pl      'podman logs'
abbr -a -- pe      'podman exec'
abbr -a -- pg      'podman generate'
abbr -a -- pgs     'podman generate systemd'
abbr -a -- pgsf    'podman generate systemd --files'
abbr -a -- pgsn    'podman generate systemd -n'
abbr -a -- pgsfn   'podman generate systemd --files -n'
abbr -a -- pimgs   'podman images'
abbr -a -- pimgsg  'podman images | grep'
abbr -a -- pimg    'podman image'
abbr -a -- pimgrm  'podman image rm'
abbr -a -- pimgr   'podman image rm'
abbr -a -- pi      'podman inspect'
abbr -a -- ppod    'podman pod'
abbr -a -- ppo     'podman pod'
abbr -a -- ppodc   'podman pod create'
abbr -a -- ppoc    'podman pod create'
abbr -a -- ppodps  'podman pod ps'
abbr -a -- ppops   'podman pod ps'
abbr -a -- ppodrm  'podman pod rm'
abbr -a -- pporm   'podman pod rm'
abbr -a -- pb      'podman build'
abbr -a -- pbt     'podman build -t'
abbr -a -- pn      'podman network'
abbr -a -- pnc     'podman network create'
abbr -a -- pnrm    'podman network rm'
abbr -a -- pnls    'podman network ls'
abbr -a -- pnl     'podman network ls'
abbr -a -- pni     'podman network inspect'
abbr -a -- pnp     'podman network prune'
abbr -a -- pv      'podman volume'
abbr -a -- pvc     'podman volume create'
abbr -a -- pve     'podman volume export'
abbr -a -- pvl     'podman volume ls'
abbr -a -- pvls    'podman volume ls'
abbr -a -- pvi     'podman volume inspect'
## docker compose
abbr -a -- dc      'docker compose'
abbr -a -- dc0     'docker compose stop'
abbr -a -- dc1     'docker compose start'
abbr -a -- dcu     'docker compose up'
abbr -a -- dcub    'docker compose up --build'
abbr -a -- pc      'docker compose'
abbr -a -- pc0     'docker compose stop'
abbr -a -- pc1     'docker compose start'
abbr -a -- pcu     'docker compose up'
abbr -a -- pcub    'docker compose up --build'
## containers
abbr -a -- p1g     'podman start graphdb'
abbr -a -- p0g     'podman stop graphdb'
