## system
abbr -a -- sy     'systemctl'
abbr -a -- sen    'systemctl enable'
abbr -a -- senn   'systemctl enable --now'
abbr -a -- sd     'systemctl disable'
abbr -a -- s1     'systemctl start'
abbr -a -- s0     'systemctl stop'
abbr -a -- s01    'systemctl restart'
abbr -a -- ss     'systemctl status'
abbr -a -- sedi   'systemctl edit'
abbr -a -- sdr    'sudo systemctl daemon-reload'
abbr -a -- sc     'systemctl cat'
## user
abbr -a -- suen   'systemctl --user enable'
abbr -a -- suenn  'systemctl --user enable --now'
abbr -a -- sud    'systemctl --user disable'
abbr -a -- su1    'systemctl --user start'
abbr -a -- su0    'systemctl --user stop'
abbr -a -- su01   'systemctl --user restart'
abbr -a -- sus    'systemctl --user status'
abbr -a -- sued   'systemctl --user edit'
abbr -a -- suedi  'systemctl --user edit'
abbr -a -- sudr   'systemctl --user daemon-reload'
abbr -a -- suc    'systemctl --user cat'
