## general
abbr -a -- w1    'hwatch -ctn1 -s \'fish -c\' -p'
abbr -a -- h     'hwatch -ctn1 -s \'fish -c\' -p'
abbr -a -- h1    'hwatch -ctn1 -s \'fish -c\' -p'
abbr -a -- hw    'hwatch -ctn1 -s \'fish -c\' -p'
abbr -a -- hw1   'hwatch -ctn1 -s \'fish -c\' -p'
## podman
abbr -a -- wpps  'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- hpps  'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- hwpps 'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- wp    'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- hp    'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- hwp   'hwatch -ctn1 -s \'fish -c\' -p "podman ps --format \'$PODMAN_FORMATTING\'"'
abbr -a -- wpl   'hwatch -ctn1 -s \'fish -c\' -p podman logs'
## lsd
abbr -a -- wl    'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hl    'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hwl   'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- wls   'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hls   'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hwls  'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- wlsd  'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hwlsd 'hwatch -ctn1 -s \'fish -c\' -p lsd'
abbr -a -- hlsd  'hwatch -ctn1 -s \'fish -c\' -p lsd'
## bat
abbr -a -- wb    'hwatch -ctn1 -s \'fish -c\' -p bat'
abbr -a -- hb    'hwatch -ctn1 -s \'fish -c\' -p bat'
abbr -a -- hwb   'hwatch -ctn1 -s \'fish -c\' -p bat'
