abbr -a -- cd    'z'
abbr -a -- zq    'zoxide query -l'
abbr -a -- zqa   'zoxide query -als'
abbr -a -- zals  'zoxide query -als'
abbr -a -- zqal  'zoxide query -als | less'
abbr -a -- zalsl 'zoxide query -als | less'
abbr -a -- zqag  'zoxide query -als | grep'
abbr -a -- zalsg 'zoxide query -als | grep'
abbr -a -- zr    'zoxide remove'
