- name: Install Obsidian
  import_tasks: ../tasks/yay.yml
  vars:
    package_s: obsidian

- name: Create obsidian dir(s)
  file:
    path: '{{obsi_path}}'
    state: directory
    mode: "0755"

- name: Check if obsidian repo already exists
  stat:
    path: '{{obsi_path}}/.git'
  register: obsi_git

- name: Check if .obsidian  already exists
  stat:
    path: '{{obsi_path}}/.obsidian'
  register: obsi_dot

- name: Clone repo
  git:
    repo: 'git@github.com:{{git_username}}/{{obsi_repo}}.git'
    dest: '{{obsi_path}}'
    key_file: '{{git_ssh_key}}'
    accept_hostkey: true
  become: true
  become_user: '{{linux_user}}'
  when: not obsi_git.stat.exists

- name: Re-establish .obsidian
  copy:
    src: .obsidian
    dest: '{{obsi_path}}'
  when: not obsi_dot.stat.exists
