- name: Install Obsidian
  kewlfft.aur.aur:
    name: obsidian
    state: present
- name: Create obsi dir(s)
  file:
    path: '{{obsi_dir}}'
    state: directory
    mode: "0755"
    
- name: Clone repo
  git:
    repo: 'git@github.com:{{git_username}}/{{obsi_repo}}.git'
    dest: '{{obsi_dir}}'