- name: Install Obsidian
  kewlfft.aur.aur:
    name: obsidian
    state: present
  become: true
  become_user: '{{linux_user}}'
  tags:
    - obsidian
    - install

- name: Create obsidian dir(s)
  file:
    path: '{{obsi_path}}'
    state: directory
    mode: "0755"
  tags:
    - obsidian

- name: Check if obsidian repo already exists
  stat:
    path: '{{obsi_path}}/.git'
  register: obsi_git
  tags:
    - obsidian

- name: Check if .obsidian  already exists
  stat:
    path: '{{obsi_path}}/.obsidian'
  register: obsi_dot
  tags:
    - obsidian

- name: Clone repo
  git:
    repo: 'git@github.com:{{git_username}}/{{obsi_repo}}.git'
    dest: '{{obsi_path}}'
    key_file: '{{git_ssh_key}}'
    accept_hostkey: true
  become: true
  become_user: '{{linux_user}}'
  when: not obsi_git.stat.exists
  tags:
    - obsidian
    - git
    - clone

- name: Re-establish .obsidian
  copy:
    src: .obsidian
    dest: '{{obsi_path}}'
  when: not obsi_dot.stat.exists
  tags:
    - obsidian
