- name: Install Fish Shell
  import_tasks: ../tasks/yay.yml
  vars:
    package_s: fish
  tags: [fish, shell]

- name: Establish Config
  copy:
    src: config.fish
    dest: '{{fish_path}}/config.fish'
    mode: '0644'
  tags: [shell, fish, conf]

- name: Add fish to valid shells
  lineinfile:
    path: /etc/shells
    line: /usr/bin/fish
    state: present
  become: true
  tags: [shell, fish, establish]

- name: Set fish as default shell
  user:
    name: '{{linux_user}}'
    shell: /usr/bin/fish
  become: true
  tags:
    - shell
    - fish
    - establish

- name: Check if Fisher Exists
  stat:
    path: '{{fish_path}}/functions/fisher.fish'
  register: fisher
  failed_when: false
  changed_when: false
  tags: [shell, fish, check]

- name: Establish Fisher extension # noqa: command-instead-of-module
  shell: |
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher install jorgebucaran/fisher
  args:
    executable: fish
  when: not fisher.stat.exists
  tags: [shell, fish, establish]

- name: Check if Tide exists
  command: fish -c 'type -q tide'
  register: is_tide
  failed_when: false
  changed_when: false
  tags: [shell, fish, check]

- name: Install Tide
  command: fish -c 'fisher install IlanCosman/tide@v6'
  when: is_tide.rc != 0
  tags: [shell, fish, install]

- name: Configure Tide
  shell: |
    tide configure --auto \
      --style=Rainbow \
      --prompt_colors='True color' \
      --show_time=No \
      --rainbow_prompt_separators=Angled \
      --powerline_prompt_heads=Slanted \
      --powerline_prompt_tails=Flat \
      --powerline_prompt_style='Two lines, character' \
      --prompt_connection=Disconnected \
      --powerline_right_prompt_frame=No \
      --prompt_spacing=Compact \
      --icons='Many icons' \
      --transient=Yes
  args:
    executable: fish
  changed_when: false
  tags: [shell, fish]

- name: Add Functions
  copy:
    src: functions/
    dest: '{{fish_path}}/functions/'
    mode: '0644'
    directory_mode: '0755'
  tags: [fish, shell, conf]

- name: Use custom command execution
  replace:
    path: '{{fish_path}}/functions/fish_prompt.fish'
    regexp: '^(bind .*)_tide_enter_transient$'
    replace: '\1__execute_commands'
  tags: [fish, shell]

- name: Add Fish Confs
  blockinfile:
    path: '{{fish_path}}/conf.d/{{file | basename}}'
    create: true
    insertafter: EOF
    marker: "# {mark} abbr"
    marker_begin: BEG
    marker_end: END
    append_newline: true
    block: '{{lookup("file", file)}}'
  with_fileglob:
    - 'conf.d/*'
  loop_control:
    loop_var: file
  tags: [fish, shell, conf]
