- name: 'clone-repo | Check if repo already exists - {{repo}}'
  stat:
    path: '{{prog_path}}/{{repo}}/.git'
  register: repo_git
  failed_when: false
  changed_when: false

- name: 'clone-repo | Git Clone {{repo}}'
  git:
    repo: 'git@github.com:{{git_username}}/{{repo}}.git'
    dest: '{{prog_path}}/{{repo}}'
    accept_hostkey: true
    key_file: '{{git_ssh_key}}'
  when: not repo_git.stat.exists
  environment:
    SSH_AUTH_SOCK: "{{lookup('env', 'SSH_AUTH_SOCK')}}"
