- name: Create Dir
  file:
    path: '{{prog_path}}'
    state: directory
    mode: '0755'

- name: 'Create Symlinks'
  file:
    src: '{{prog_path}}'
    dest: '{{user_path}}/{{ item }}/{{prog_dir}}'
    state: link
  loop:
    - Desktop
    - Documents

- name: 'Git Clone'
  include_tasks: clone-repo.yml
  loop:
    - ScrapLang
    - Orgen
    - LangCode
    - Sysiac
    - TestCore
  loop_control:
    loop_var: repo
