FROM alpine:latest AS alpine

FROM n8nio/n8n:latest

# Copy apk and its deps from Alpine

COPY --from=alpine /sbin/apk /sbin/apk

COPY --from=alpine /usr/lib/libapk.so* /usr/lib/

USER root

RUN apk add --no-cache python3 py3-pip

USER node
