schema:
  '<APP>':
    '?path':
    '?files':
      - {name: '<NAME>', '?path': '<PATH>'}
    '?dirs':
      - {name: '<NAME>', '?path': '<PATH>'}

confs:
  lsd:
    files:
      - name: config.yaml
      - name: icons.yaml
  bat:
    files:
      - name: config
  git:
    path: '{{user_path}}'
    files:
      - name: '.gitconfig'
  ssh:
    path: '{{user_path}}/.ssh'
    files:
      - name: 'config'
  vim:
    path: '{{user_path}}'
    files:
      - name: .vimrc
  nvim:
    files:
      - name: init.lua
  yay:
    files:
      - name: config.json
  grc:
    path: '{{user_path}}/.grc'
    dirs:
      - name: '.'
