confs:
  lsd:
    files:
      - config.yaml
      - icons.yaml
  bat:
    files:
      - config
  git:
    dir: '{{user_path}}'
    files:
      - '.gitconfig'
  ssh:
    dir: '{{user_path}}/.ssh'
    files:
      - 'config'
  vim:
    dir: '{{user_path}}'
    files:
      - .vimrc
  nvim:
    files:
      - init.lua
