- name: Install Priner via yay
  kewlfft.aur.aur:
    name:
      - cups
      - cups-browsed
      - cups-filters
      - cups-pdf
      - system-config-printer
    state: present
  become: true
  become_user: '{{linux_user}}'

- name: Enable services
  systemd:
    name: '{{service}}'
    enabled: true
    state: started
  loop:
    - cups
    - avahi-daemon
    - cups-browsed
  loop_control:
    loop_var: service
