- name: Configure Konsole profile
  template:
    src: profile.j2
    dest: '{{profile_path}}'
    mode: '0644'

- name: Set new Konsole profile default
  ini_file:
    path: '{{user_path}}/.config/konsolerc'
    section: Desktop Entry
    option: DefaultProfile
    value: '{{username}}.profile'

- name: Configure Konsole Font
  ini_file:
    path: '{{profile_path}}'
    section: 'Appearance'
    option: 'Font'
    value: 'Hack Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0'
