containers_path: '{{conf_path}}/containers'

base_paths:
  mounts: '/opt/podman'
  containers: '{{containers_path}}'
mount_paths:
  vaultwarden_mount: '{{base_paths.mounts}}/vaultwarden'
paths: '{{base_paths | combine(mount_paths)}}'

############################
# Central Podman Structure #
############################
podman:
  conf:
    envs:
      color: 1
    registries:
      unqualifieds: ['docker.io']
    compose:
      warning_logs: false
  paths: '{{paths}}'
  apps:
    vaultwarden:
      services:
        server:
          image: vaultwarden/server:latest
          container_name: vaultwarden
          ports: [127.0.0.1:7000:80]
          restart: unless-stopped
          volumes:
            - '{{paths.vaultwarden_mount}}/data/:/data'
            - '{{paths.vaultwarden_mount}}/ssl:/ssl:Z'
          environment:
            DOMAIN: 'https://proxpxd.vaultwarden.pl'
            ROCKET_TLS: '{certs="/ssl/localhost.pem",key="/ssl/localhost-key.pem"}'
