containers_path: '{{conf_path}}/containers'

############################
# Central Podman Structure #
############################
podman:
  conf:
    envs:
      color: 1
    registries:
      unqualifieds: ['docker.io']
    compose:
      warning_logs: false
  paths:
    mounts: '/opt/podman'
    containers: '{{containers_path}}'
      # volume:
  apps:
    vaultwarden:
      containers:
        server:
          hport: 7000
