# Paths
base_paths:
  containers: '{{conf_path}}/containers'
  mounts: '/opt/podman'
derivated_paths:
  containers_systemd: '{{base_paths.containers}}/systemd'
  vaultwarden_mount: '{{base_paths.mounts}}/vaultwarden'
  n8n_mount: '{{base_paths.mounts}}/n8n'
all_paths: '{{base_paths | combine(derivated_paths)}}'

# Ports
ports:
  n8n:
    main: 7010
    runner: 7011

############################
# Central Podman Structure #
############################
podman:
  conf:
    envs:
      color: 1
    registries:
      unqualifieds: ['docker.io']
    compose:
      warning_logs: false
  paths: '{{all_paths}}'
  apps:
    vaultwarden:
      networks:
        common:
          external: true
      services:
        vaultwarden:
          image: vaultwarden/server:latest
          container_name: vaultwarden
          ports: [127.0.0.1:7000:80]
          restart: unless-stopped
          volumes:
            - '{{all_paths.vaultwarden_mount}}/data/:/data'
            - '{{all_paths.vaultwarden_mount}}/ssl:/ssl:Z'
          environment:
            DOMAIN: 'https://proxpxd.vaultwarden.pl'
            ROCKET_TLS: '{certs="/ssl/localhost.pem",key="/ssl/localhost-key.pem"}'
          labels:
            - app=vaultwarden
            - role=app
            - vaultwarden
    n8n:
      networks:
        default:
          name: n8n-net
      volumes:
        n8n_data:
      services:
        n8n:
          image: n8n-python
          container_name: n8n
          build:
            context: .
            dockerfile: Containerfile
          ports: ['{{ports.n8n.main}}:5678']
          restart: on-failure
          volumes:
            - n8n_data:/home/node/.n8n'
          extra_hosts:
            - "host.containers.internal:host-gateway"
          environment:
            N8N_PROTOCOL: https
            N8N_HOST: '{{vault_ngrok_url}}'
            WEBHOOK_URL: '{{vault_ngrok_url}}'
            N8N_RUNNERS_MODE: external
            N8N_NATIVE_PYTHON_RUNNER: "true"
            N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
            N8N_RUNNERS_AUTH_TOKEN: '{{vault_n8n_runners_auth_token}}'
            N8N_RUNNERS_BROKER_PORT: "5679"
            N8N_RUNNERS_BROKER_LISTEN_ADDRESS: 0.0.0.0
            N8N_DIAGNOSTICS_ENABLED: "false"
            N8N_PERSONALIZATION_ENABLED: "false"
            N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
            N8N_BLOCK_ENV_ACCESS: "false"
          labels:
            - app=n8n
            - n8n
            - role=app
        n8n-runners:
          image: docker.io/n8nio/runners:latest
          container_name: n8n-runners
          ports: ['{{ports.n8n.runner}}:5679']
          restart: on-failure
          extra_hosts:
            - "host.containers.internal:host-gateway"
          environment:
            N8N_RUNNERS_AUTH_TOKEN: '{{vault_n8n_runners_auth_token}}'
            N8N_RUNNERS_TASK_BROKER_URI: http://n8n:5679
            N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT: 15
          labels:
            - app=n8n
            - n8n
        ngrok:
          image: ngrok/ngrok:latest
          container_name: ngrok
          network_mode: host
          command:
            - http
            - '--url={{vault_ngrok_domain}}'
            - '{{ports.n8n.main | string}}'
          restart: on-failure
          environment:
            NGROK_AUTHTOKEN: '{{vault_ngrok_authtoken}}'
          labels:
            - net
            - n8n
