- name: Workstation
  hosts: localhost
  connection: local
  roles:
    - role: setup
      tags: [setup]
    # Core/Common
    - role: libs
      tags: [libs]
    - role: basic-tools
      tags: [basic-tools]
    - role: printers
      tags: [printers]
    - role: fonts
      tags: [fonts]
    - role: konsole
      tags: [konsole]
    - role: fish
      tags: [fish, shell]
    - role: fcitx
      tags: [fcitx]
    - role: podman
      tags: [podman]
    - role: zoxide
      tags: [zoxide]
    # Linux UI
    - role: virtual-desktops
      tags: [virtual-desktops]
    - role: shortcuts
      tags: [shortcuts]
    # Apps
    - role: firefox
      tags: [firefox]
    - role: obsidian
      tags: [obsidian]
    - role: simple-conf-apps
      tags: [simple-apps]
    - role: dolphin
      tags: [dolphin]
    - role: vaultwarden
      tags: [vaultwarden]
    - role: bluetooth
      tags: [bluetooth]
    # Own Creations
    - role: own-repos
      tags: [own-repos]
