- name: Workstation
  hosts: localhost
  connection: local
  roles:
    - setup
    # Core/Common
    - hardware
    - basic-tools
    - fonts
    - konsole
    - shell
    # Linux UI
    - virtual-desktops
    - shortcuts
    # Apps
    - firefox
    - obsidian
    - simple-conf-apps
    - own-repos
