- name: Install Fish Shell
  import_tasks: ../tasks/yay.yml
  vars:
    package_s: fish

- name: Establish Config
  copy:
    src: config.fish
    dest: '{{fish_path}}/config.fish'
    mode: '0644'

- name: Add fish to valid shells
  lineinfile:
    path: /etc/shells
    line: /usr/bin/fish
    state: present
  become: true

- name: Set fish as default shell
  user:
    name: '{{linux_user}}'
    shell: /usr/bin/fish
  become: true

- name: Check if Fisher Exists
  stat:
    path: '{{fish_path}}/functions/fisher.fish'
  register: fisher
  failed_when: false
  changed_when: false

- name: Establish Fisher extension # noqa: command-instead-of-module
  shell: |
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher install jorgebucaran/fisher
  args:
    executable: fish
  when: not fisher.stat.exists

- name: Check if Tide exists
  command: fish -c 'type -q tide'
  register: is_tide
  failed_when: false
  changed_when: false

- name: Install Tide
  command: fish -c 'fisher install IlanCosman/tide@v6'
  when: is_tide.rc != 0

- name: Configure Tide
  shell: |
    tide configure --auto \
      --style=Rainbow \
      --prompt_colors='True color' \
      --show_time=No \
      --rainbow_prompt_separators=Angled \
      --powerline_prompt_heads=Slanted \
      --powerline_prompt_tails=Flat \
      --powerline_prompt_style='Two lines, character' \
      --prompt_connection=Disconnected \
      --powerline_right_prompt_frame=No \
      --prompt_spacing=Compact \
      --icons='Many icons' \
      --transient=Yes
  args:
    executable: fish
  changed_when: false

- name: Add Functions
  copy:
    src: functions/
    dest: '{{fish_path}}/functions/'
    mode: '0644'
    directory_mode: '0755'

- name: Use custom command execution
  replace:
    path: '{{fish_path}}/functions/fish_prompt.fish'
    regexp: '^(bind .*)_tide_enter_transient$'
    replace: '\1__execute_commands'

- name: Set Fish Envs
  include_tasks: ../tasks/add-fish-conf.yml
  vars:
    file_s: fish
    pos: EOF
    blockname: colors
    content: |
      set -gx fish_color_autosuggestion brblack
      set -gx fish_color_command normal
      set -gx fish_color_comment brgreen
      set -gx fish_color_quote bryellow
      set -gx fish_color_param brgreen
      set -gx fish_color_cwd brblue
      set -gx fish_color_end brblue

- name: Add Apps Fish Conf Per Type
  include_tasks:
    file: ../tasks/add-fish-conf.yml
    apply:
      tags: [fish, confd]
  vars:
    file_s: '{{file}}'
    pos: EOF
    blockname: '{{file.src | dirname | basename}}'
  loop: "{{query('filetree', role_path ~ '/files/conf.d')}}"
  loop_control:
    loop_var: file
  when: file.state == 'file'
  tags: [fish, confd]
