---
# file_s: string(extensionless if content) | fullpath to file | fullpath to directory
# pos: 'EOF' | 'BOF'
# content: file's content
# blockname: what to put in the inserted blocks (default: envs)

- name: Add Fish Conf | Set Facts ()
  set_fact:
    safe_pos: '{{pos | default("BOF")}}'
    safe_blockname: "{{blockname | default('envs')}}"
    files: >-
      {{
        [file_s] if file_s is string or file_s.state == 'file' else
        (query('community.general.filetree', file_s.src) | selectattr('state', 'eq', 'file'))
      }}
    paths: []
  no_log: true

- name: Add Fish Conf | Set Paths as Strings with .fish Ending
  set_fact:
    paths: "{{paths | default([]) + [item.src | default(item) | regex_replace('(?<!\\.fish)$', '.fish') ]}}"
  loop: "{{files}}"
  no_log: true

- name: Add Fish Conf | Add
  blockinfile:
    path: "{{fish_path}}/conf.d/{{path | basename}}"
    create: true
    marker: '# {mark} {{safe_blockname}}'
    marker_begin: BEG
    marker_end: END
    append_newline: true
    insertafter: "{{'EOF' if safe_pos == 'EOF' else omit}}"
    insertbefore: "{{'BOF' if safe_pos == 'BOF' else omit}}"
    block: "{{content if content is defined else lookup('file', path)}}"
  tags: [fish, shell, conf]
  loop: '{{paths}}'
  loop_control:
    loop_var: path
