---
- name: Add Fish Conf | Set paths | String
  set_fact:
    paths: ['{{file_s}}.fish']
  when: (file_s | type_debug) == 'str'
  tags: [facts, conf]

- name: Set paths | File
  set_fact:
    paths: '{{file_s.src}}'
  when:
    - (file_s | type_debug) == 'dict'
    - file_s.state == 'file'
  tags: [facts, conf]

- name: Set paths | Dictionary
  set_fact:
    paths: >-
      {{
        query('community.general.filetree', file_s.src)
         | selectattr('state', 'eq', 'file')
         | map(attribute='src')
         | list
      }}
  when:
    - (file_s | type_debug) == 'dict'
    - file_s.state != 'ditionary'
  tags: [facts, conf]

- name: Add Fish Conf | Set Facts
  set_fact:
    safe_pos: '{{pos | default("BOF")}}'
    safe_blockname: "{{blockname | default('envs')}}"

- name: Add Fish Conf | Set Facts 1
  set_fact:
    paths: >-
      {{
        [file_s ~ '.fish'] if file_s is not mapping else
        [file_s.src | string] if file_s.state == 'file' else
        []
      }}
  no_log: false
  tags: [facts, conf]

        # (query('community.general.filetree', file_s.src)
        # | selectattr('state', 'eq', 'file')
        # | map(attribute='src')
        # | list)

- name: 'Add Fish Conf | Debug'
  debug:
    msg:
      - "file_s: {{file_s}}"
      - "file_s type: {{file_s | type_debug}}"
      - "is_string: {{file_s is string}}"
      - "is_mapping: {{file_s is mapping}}"
      # - "file_s_type: {{file_s_type}}"
      # - "is_string: {{is_string}}"
      # - "is_mapping: {{is_mapping}}"
      - "file_s.src: {{file_s.src | default('no src')}}"
      - "paths: {{paths}}"
      # - "paths2: {{paths2}}"
      - "fuck = {{[file_s ~ '.fish'] if file_s is string else [file_s.src] if file_s.src is file else query('filetree', file_s.src) | selectattr('state', 'eq', 'file') | map(attribute='src') | list}}"
  tags: [fish, shell]

- name: Add Fish Conf | Add
  blockinfile:
    path: "{{fish_path}}/conf.d/{{path}}"
    create: true
    marker: '# {mark} {{safe_blockname}}'
    marker_begin: BEG
    marker_end: END
    append_newline: true
    insertafter: "{{'EOF' if safe_pos == 'EOF' else omit}}"
    insertbefore: "{{'BOF' if safe_pos == 'BOF' else omit}}"
    block: "{{content if content is defined else lookup('file', path)}}"
  tags: [fish, shell, conf]
  loop: '{{paths}}'
  loop_control:
    loop_var: path
