---
- name: Append Fish Conf |
  blockinfile:
    path: '{{fish_path}}/conf.d/{{filename}}.fish'
    create: true
    insertafter: EOF
    marker: '# {mark} {{blockname | default("abbr")}}'
    marker_begin: BEG
    marker_end: END
    append_newline: true
    block: '{{content}}'
  loop: '{{[filename_s] if filename_s is string else filename_s}}'
  loop_control:
    loop_var: filename
  tags: [fish, shell, conf]
