---
- name: Prepend Fish Conf |
  blockinfile:
    path: '{{fish_path}}/conf.d/{{filename}}.fish'
    create: true
    insertbefore: BOF
    marker: '# {mark} {{blockname | default("envs")}}'
    marker_begin: BEG
    marker_end: END
    block: '{{content}}'
  tags: [fish, shell, conf]
