- name: Install Firefox
  kewlfft.aur.aur:
    name: firefox
    state: present
  tags:
    - firefox
    - install

- name: Ensure local applications directory
  file:
    path: '{{ user_dir }}/.local/share/applications'
    state: directory
    mode: '0755'
  tags:
    - firefox
    - prepare

- name: Copy Firefox desktop entry
  copy:
    src: /usr/share/applications/firefox.desktop
    dest: '{{ user_dir }}/.local/share/applications/firefox.desktop'
    mode: '0644'
    force: false
  tags:
    - firefox
    - conf

- name: Enable Firefox NVIDIA offload and Wayland
  lineinfile:
    path: '{{ user_dir }}/.local/share/applications/firefox.desktop'
    regexp: '^Exec=.*'
    line: 'Exec=env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia MOZ_ENABLE_WAYLAND=1 firefox %u'
  tags:
    - firefox
    - conf

- name: Set Firefox as default browser
  command:
    cmd: xdg-settings set default-web-browser firefox.desktop
  changed_when: false
  tags:
    - firefox
    - conf
