- name: Install Terminal Tools
  kewlfft.aur.aur:
    name:
      - jq
      - yq
      - viu
      - fzf
      - cheat
      - zip
      - lsof
    state: present
  become: true
  become_user: '{{linux_user}}'
  tags:
    - install
    - common
