- name: Install Apps via yay
  kewlfft.aur.aur:
    name:
      - viu
      - fzf
      - cheat
      - zip
      - lsof
      - gzip
      - gtop
      - gping
      - fd
      - lolcat
      - renameutils

      - lsd
      - bat
      - git
      - neovim
      - yt-dlp
      - yt-dlp-ejs

      - libreoffice-still
      - gimp
      - gparted
      - telegram-desktop-bin
      - signal-desktop-beta-bin
    state: present
  become: true
  become_user: '{{linux_user}}'

- name: Install Apps via npm
  npm:
    name: '{{item}}'
    global: true
  become: true
  loop:
    - "@tagspaces/shell"

- name: Create App Confs
  include_tasks: establish-confs.yml
  loop_control:
    loop_var: app
  loop: "{{confs | dict2items(key_name='name', value_name='conf')}}"
