# abbr
abbr -a -- tsk     'task'
abbr -a -- tk      'task'
abbr -a -- tl      'task peek'
abbr -a -- tp      'task peek'
abbr -a -- tla     'task view'
abbr -a -- tv      'task view'
abbr -a -- ta      'task add'
abbr -a -- ts      'task show'
abbr -a -- tsg     'task show | grep'
abbr -a -- tc      'task config'
abbr -a -- tcr     'task config report'
abbr -a -- tu      'task undo'
abbr -a -- te      'task export'
abbr -a -- tej     'task export | jq'
abbr -a -- tejq    'task export | jq'
abbr -a -- ti      'task import'
abbr -a -- tcal    'task calendar'
abbr -a -- tclean  'task status:deleted purge'
abbr -a -- tkr     'task remove'

abbr -a -- tcol    'task show report | grep columns | choose 1 | string split , | sort | uniq'
abbr -a -- tcols   'task show report | grep columns | choose 1 | string split , | sort | uniq'
abbr -a -- tcolors 'task rc.color=on rc._forcecolor=1 color legend'