abbr -a -- c       'conda'
abbr -a -- co      'conda'
abbr -a -- con     'conda'
abbr -a -- cond    'conda'
abbr -a -- a       'conda activate'
abbr -a -- ca      'conda activate'
abbr -a -- cac     'conda activate ( ls $CONDA_ENVS | grep common )'
abbr -a -- cend    'conda deactivate'
abbr -a -- cdeact  'conda deactivate'
abbr -a -- cdeac   'conda deactivate'
abbr -a -- cdea    'conda deactivate'
abbr -a -- cde     'conda deactivate'
abbr -a -- cda     'conda deactivate'
abbr -a -- deact   'conda deactivate'
abbr -a -- deac    'conda deactivate'
abbr -a -- dea     'conda deactivate'
abbr -a -- de      'conda deactivate'
abbr -a -- da      'conda deactivate'
abbr -a -- cl      'conda list'
abbr -a -- clg     'conda list | grep'
abbr -a -- cel     'conda env list'
abbr -a -- cee     'conda env export'
abbr -a -- ceu     'conda env update'
abbr -a -- ceuf    'conda env update --file'
abbr -a -- ceupf   'conda env update --prune --file'
abbr -a -- ci      'conda install'
abbr -a -- cif     'conda install --file'
abbr -a -- cu      'conda uninstall'
abbr -a -- cc      'conda create'
abbr -a -- ccn     'conda create -n'
abbr -a -- cconf   'conda config'
abbr -a -- cconfs  'conda config --show'
abbr -a -- cconfsc 'conda config --show channels'
abbr -a -- cconfa  'conda config --append'
abbr -a -- cconfac 'conda config --append channels'
abbr -a -- cconfr  'conda config --remove'
abbr -a -- cconfrc 'conda config --remove channels'
abbr -a -- cr      'conda remove'
abbr -a -- crn     'conda remove -n'
abbr -a -- cran    'conda remove --all -n'
abbr -a -- crna    'conda remove -n --all'
abbr -a -- crf     'conda remove --force'
abbr -a -- cup     'conda update'
