- name: Install Obsidian
  kewlfft.aur.aur:
    name: obsidian
    state: present
  become: true
  become_user: '{{linux_user}}'
  tags:
    - obsidian
    - install

- name: Create obsidian dir(s)
  file:
    path: '{{obsi_dir}}'
    state: directory
    mode: "0755"
  tags:
    - obsidian
    - conf

- name: Check if obsidian repo already exists
  stat:
    path: '{{ obsi_dir }}/.git'
  register: obsi_git

- name: Clone repo
  git:
    repo: 'git@github.com:{{git_username}}/{{obsi_repo}}.git'
    dest: '{{obsi_dir}}'
    key_file: '{{git_ssh_key}}'
    accept_hostkey: true
  become: false
  become_user: '{{linux_user}}'
  when: not obsi_git.stat.exists
